#!/bin/bash

# Globals
CONFIG_FILE=/etc/fdnsc.conf
URL_BASE=https://freedns.afraid.org/dynamic/update.php

# Defaults
DEFAULT_PID_FILE=/run/fdnsc.pid
PID_FILE="$DEFAULT_PID_FILE"
DEFAULT_LOG_FILE=/var/log/fdnsc.log
LOG_FILE="$DEFAULT_LOG_FILE"
DEFAULT_UPDATE_PERIOD=3600
UPDATE_PERIOD="$DEFAULT_UPDATE_PERIOD"

# Read config file
if [ -f "$CONFIG_FILE" ]; then
  . "$CONFIG_FILE"
else
  echo "$CONFIG_FILE does not exist. FDNSC requires UPDATE_HASH configured."
  exit 1
fi

usage() {
  cat << EOF
Usage: fdnsc [ACTION]

FDNSC is a freedns.afraid.org dynamic DNS update client.

FDNSC reads from "$CONFIG_FILE".  It is sourced as a regular Bash sript.

Required config variables:
UPDATE_HASH   - The hash from your direct update URL.  This is everything after
                the ?.  It can be found at https://freedns.afraid.org/dynamic.

Optional config variables:
PID_FILE      - The file to save the process id (default: "$DEFAULT_PID_FILE")
LOG_FILE      - The log file to write to (default: "$DEFAULT_LOG_FILE")
UPDATE_PERIOD - The update period in seconds (default: "$DEFAULT_UPDATE_PERIOD")
EOF
}

# Check the requested action
action=start
[ $# -eq 1 ] && action="$1"
[ $# -gt 1 ] && usage && exit 1
[ "$action" != start -a "$action" != stop ] && usage && exit 1

if [ $action = start ]; then
  # Check if another process is running
  if [ -e "$PID_FILE" ]; then
    cat << EOF
$PID_FILE already exists.  Check if another process is running.
If not, delete $PID_FILE and restart FDNSC.
EOF
    exit 1
  fi

  # Make sure UPDATE_HASH is set
  [ -z "$UPDATE_HASH" ] && usage && exit 1

  # Store our PID
  echo $$ > "$PID_FILE"

  # Start updating
  while [ 1 ]; do
    FDNS=$(wget -q -O - "$URL_BASE?$UPDATE_HASH")
    echo "$FDNS" >> "$LOG_FILE"
    sleep "$UPDATE_PERIOD"
  done

else # action must be stop

  # Make sure another process is running
  if [ ! -e "$PID_FILE" ]; then
    echo "$PID_FILE does not exist.  Has FDNSC been started?"
    exit 1
  fi

  # Another process is running.  Grab its PID
  pid="`cat $PID_FILE`"

  # Kill it off
  kill "$pid"

  # Delete the PID file
  rm -f "$PID_FILE"

fi
